name: 'Azure Deployment'
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:

jobs:
  #######
  # Terraform_Azure_Resources Dev #
  #######
  DevTerraformCheck:
    name: Terraform Azure Resources Dev Check
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/check-terraform.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./terraform_azure_resources
  
  DevTerraformDeployment:
    name: Terraform Azure Resources Dev Deployment
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./terraform_azure_resources
  #######
  # Lab1 Dev #
  #######
  Lab1TFCheck:
    name: Terraform Lab1 Dev Check
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/check-terraform.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab1
  
  Lab1DevTerraformDeployment:
    name: Terraform Lab1 Dev Deployment
    needs: ["DevTerraformDeployment"]
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab1

  #######
  # Lab2 Dev #
  #######
  Lab2TFCheck:
    name: Terraform Lab2 Dev Check
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/check-terraform.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab2
  
  Lab2DevTerraformDeployment:
    name: Terraform Lab2 Dev Deployment
    needs: ["Lab1DevTerraformDeployment"]
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab2

  #######
  # Lab3 Dev #
  #######
  Lab3TFCheck:
    name: Terraform Lab3 Dev Check
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/check-terraform.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab3
  
  Lab3DevTerraformDeployment:
    name: Terraform Lab3 Dev Deployment
    needs: ["Lab2DevTerraformDeployment"]
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab3