name: 'Lab1 Deployment'
on:   
  workflow_run:
    workflows: ["Azure Deployment"]
    types:
      - completed
  workflow_dispatch:

jobs:
  #######
  # Lab1 Dev #
  #######
  Lab1TFCheck:
    name: Terraform Lab1 Dev Check
    if: github.event_name == 'workflow_run' && github.ref_name == 'create-tf-resource'
    uses: ./.github/workflows/check-terraform.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab1
  
  Lab1DevTerraformDeployment:
    name: Terraform Lab1 Dev Deployment
    if: github.event_name == 'workflow_run' && github.ref_name == 'main'
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab1