name: 'Lab2 Deployment'
on:   
  workflow_run:
    workflows: ["Lab1 Deployment"]
    types:
      - completed
  workflow_dispatch:

jobs:
  #######
  # Lab2 Dev #
  #######
  Lab2TFCheck:
    name: Terraform Lab2 Dev Check
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/check-terraform.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab2
      TF_PLAN: false
  
  Lab2DevTerraformDeployment:
    name: Terraform Lab2 Dev Deployment
    needs:  [Lab2TFCheck]
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab2