name: 'Lab3 Deployment'
on:   
  workflow_run:
    workflows: ["Lab2 Deployment"]
    types:
      - completed
  workflow_dispatch:

jobs:
  #######
  # Lab3 Dev #
  #######
  Lab3TFCheck:
    name: Terraform Lab3 Dev Check
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/check-terraform.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab3
      TF_PLAN: false
  
  Lab3DevTerraformDeployment:
    name: Terraform Lab3 Dev Deployment
    needs:  [Lab3TFCheck]
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: development
      TF_ENVIRONMENT: dev
      WORKSPACE: ./lab3