name: 'TF State Plan and Apply'

on:
  workflow_call:
    inputs:
      TF_ENVIRONMENT:
        required: true
        type: string
      GH_ENVIRONMENT:
        required: true
        type: string
      WORKSPACE:
        required: true
        type: string

permissions:
  id-token: write
  contents: read


concurrency: tf_${{ inputs.GH_ENVIRONMENT }}

jobs:
  TerraformPlan:
    name: Terraform Plan - ${{ inputs.GH_ENVIRONMENT }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.GH_ENVIRONMENT  }}
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    #   - uses: hashicorp/setup-terraform@v3
    #     with:
    #       terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Terraform Init
        working-directory: ${{ inputs.WORKSPACE }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.WORKSPACE }}
        run: terraform plan -input=false -var-file=env/${{ inputs.TF_ENVIRONMENT }}/${{ inputs.TF_ENVIRONMENT }}.tfvars

  TerraformApproval:
    name: Manual Approval - ${{ inputs.GH_ENVIRONMENT }}
    needs: [TerraformPlan]
    runs-on: ubuntu-latest
    environment: ${{ inputs.GH_ENVIRONMENT }}-approval-group
    steps:
      - name: Display GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  TerraformApply:
    name: Terraform Apply - ${{ inputs.GH_ENVIRONMENT }}
    needs: [TerraformApproval]
    runs-on: ubuntu-latest
    environment: ${{ inputs.GH_ENVIRONMENT  }}
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    #   - uses: hashicorp/setup-terraform@v3
    #     with:
    #       terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Terraform Init
        working-directory: ${{ inputs.WORKSPACE }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.WORKSPACE }}
        run: terraform apply -input=false -var-file=env/${{ inputs.TF_ENVIRONMENT }}/${{ inputs.TF_ENVIRONMENT }}.tfvars